---
title: "GLM 1"
author: "Timothee Bonnet"
date: "18 May 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(performance)
```


## Failure of linear models

That's a typical linear model (linear regression) performing okay:
```{r}
set.seed(123)
x <- rnorm(20)
y <- 1 + x + rnorm(20)

datlinear <- data.frame(x=x, y=y)
lm0 <- lm(y~x, data = datlinear)
  
ggplot(datlinear, aes(x=x, y=y))+
geom_smooth(method="lm") + geom_point() +
geom_segment(aes(x=x, y=y, xend= x, yend=lm0$fitted.values))

check_model(lm0)

```

Now a model with the same structure, but fitted to binary data different data has more questionable performance:
```{r}
set.seed(123)
x <- rnorm(30)
latent <- 1 + 2*x + rnorm(30, sd = 0.5)
y <- 1/(1+exp(-latent))
obs <- sapply(y, FUN=function(x){rbinom(1,1,x)})

datbinary <- data.frame(x=x, y=obs)
lm1 <- lm(y~x, data = datbinary)

ggplot(datbinary, aes(x=x, y=y))+
geom_smooth(method="lm", fullrange=TRUE) + geom_point() +
geom_segment(aes(x=x, y=y, xend= x, yend=lm1$fitted.values)) +
  xlim(c(-3,2))

check_model(lm1)


```

